{
 "title": "Open5GS",
 "time": { "from": "2023-12-03T19:37:50.543Z", "to": "2023-12-03T21:37:50.543Z" },
 "panels": [
  {
   "title": "UPF Active Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr{job=\"open5gs-upfd1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amf_session{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected gNodeBs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnb{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN User Equipment",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ran_ue{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-upfd1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Data Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(fivegs_ep_n3_gtp_indatavolumeqosleveln3upf{job=\"open5gs-upfd1\"}[$__rate_interval])",
     "legendFormat": "fivegs_ep_n3_gtp_indatavolumeqosleveln3upf"
    },
    {
     "expr": "rate(fivegs_ep_n3_gtp_outdatavolumeqosleveln3upf{job=\"open5gs-upfd1\"}[$__rate_interval])",
     "legendFormat": "fivegs_ep_n3_gtp_outdatavolumeqosleveln3upf"
    }
   ]
  }
 ]
}