{
 "title": "Open5GS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UPF Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr{job=\"open5gs-upfd1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amf_session{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected gNodeBs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnb{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAN User Equipment",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ran_ue{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-amfd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"open5gs-upfd1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Packets",
   "type": "timeseries",
   "description": "Number of in/outcoming GTP data packets on the N3 interface.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_ep_n3_gtp_indatapktn3upf{job=\"open5gs-upfd1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_ep_n3_gtp_outdatapktn3upf{job=\"open5gs-upfd1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}