global:
  scrape_interval: 5s

scrape_configs:
  - job_name: open5gs-amfd
    static_configs:
      - targets: ["192.168.3.20:9091"]
  - job_name: open5gs-pcfd
    static_configs:
      - targets: ["192.168.3.20:9092"]
  - job_name: open5gs-smfd1
    static_configs:
      - targets: ["192.168.3.20:9091"]
  - job_name: open5gs-upfd1
    static_configs:
      - targets: ["192.168.3.20:9093"]
